import { EnvironmentProviders, Provider } from '@angular/core';
import { ActivatedRoute, Router, convertToParamMap, provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { ConfirmationService, MessageService } from 'primeng/api';

/**
 * Providers required to instantiate a component or a service under TestBed.
 *
 * Most specs were generated by the Angular CLI and only assert toBeTruthy(),
 * which meant none of them ever ran. TestBed had no HttpClient, so injecting a
 * component that depends on a service threw NullInjectorError before the
 * assertion was reached: the suite reported 33 failures out of 41 specs.
 *
 * Two details matter for correctness rather than for making a test pass:
 *
 * - provideHttpClient is paired with provideHttpClientTesting so an outgoing
 *   request is captured instead of leaving the machine. Order matters, the
 *   testing backend is registered after the real one.
 *
 * - ActivatedRoute is a stub with empty param and query maps, because the
 *   components read route parameters synchronously from ngOnInit.
 */
export function provideTestDependencies(
  overrides: Array<Provider | EnvironmentProviders> = []
): Array<Provider | EnvironmentProviders> {
  const emptyParams = convertToParamMap({});

  return [
    provideHttpClient(withInterceptorsFromDi()),
    provideHttpClientTesting(),
    // A real Router on an empty route table, not a hand written stub: components
    // call Router.createUrlTree and subscribe to Router.events, and a partial
    // stub fails in ways that look like application bugs.
    provideRouter([]),
    {
      provide: ActivatedRoute,
      useValue: {
        snapshot: {
          paramMap: emptyParams,
          queryParamMap: emptyParams,
          params: {},
          queryParams: {},
          data: {},
        },
        paramMap: emptyParams,
        queryParamMap: emptyParams,
        params: {},
        queryParams: {},
        data: {},
      },
    },
    {
      provide: MatDialogRef,
      useValue: {
        close: () => {},
        afterClosed: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }),
      },
    },
    { provide: MAT_DIALOG_DATA, useValue: {} },
    MessageService,
    ConfirmationService,
    ...overrides,
  ];
}